### ISSUE TITLE
Logging and databases

### ISSUE THREAD

**Issue by feldrim** [mithunvp/ContactsAPI#1]
Can we add logging and database features for a ContactsApi v2?

**Comment by mithunvp** [comment]
At present I am working on this to connect to database using EF Core, lookout by EOD.

**Comment by feldrim** [comment]
The Core has its own logging features but there are not enough sources for that. At least, I couldn't manage it when I try to implement Microsoft.Extensions.Logging to ContactsAPI. That's because I'm totally new and ASP.NET Core documentation couldn't help enough. But your ContactsAPI is really a good start and I'd love to work on that on other stuff like logging at first, database and many other things afterwards. I'll be waiting, thanks for your kindness.

**Comment by mithunvp** [comment]
I have updated repo with EF Core, basic things are working. You can work on that more, I will keep updating the repo. For logging i will post ASAP.

**Comment by feldrim** [comment]
Thank you. I'm checking that out immediately.

**Comment by mithunvp** [comment]
Check out latest commits
